language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - preranmelanta@gmail.com
      - preranmelanta@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
